//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace Models
{
    using System;

    public partial class clsConference
    {
        #region Fields
        public static string Conference_ID = "Conference_ID";
        public static string KFUPMID = "KFUPMID";
        public static string Year = "Year";
        public static string Conference_Name = "Conference_Name";
        public static string Conference_Location = "Conference_Location";
        public static string Start_Date = "Start_Date";
        public static string End_Date = "End_Date";
        public static string Paper_Presentation = "Paper_Presentation";
        public static string Paper_Title = "Paper_Title";
        public static string Authors = "Authors";
        public static string Affiliation = "Affiliation";
        public static string Project_Code = "Project_Code";
        public static string CreatedOn = "CreatedOn";
        public static string CreatedBy = "CreatedBy";
        public static string UpdatedOn = "UpdatedOn";
        public static string UpdatedBy = "UpdatedBy";
        public static string Active_flag = "Active_flag";
        public static string Deleted_flag = "Deleted_flag";
        #endregion
    }

    public partial class ConferenceController
    {
        #region Fields
        public int Conference_ID { get; set; }
        public double? KFUPMID { get; set; }
        public double? Year { get; set; }
        public string Conference_Name { get; set; }
        public string Conference_Location { get; set; }
        public DateTime? Start_Date { get; set; }
        public DateTime? End_Date { get; set; }
        public int? Paper_Presentation { get; set; }
        public string Paper_Title { get; set; }
        public string Authors { get; set; }
        public string Affiliation { get; set; }
        public string Project_Code { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool? Active_flag { get; set; }
        public bool? Deleted_flag { get; set; }
        #endregion

        #region Methods
        #endregion
    }
}
