//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;

    public partial class clsGraduateStudent
    {
        #region Fields
        public static string GraduateStudentID = "GraduateStudentID";
        public static string AdvisorID = "AdvisorID";
        public static string StudentID = "StudentID";
        public static string StudentName = "StudentName";
        public static string StudentDepartmentCode = "StudentDepartmentCode";
        public static string Nationality = "Nationality";
        public static string Degree = "Degree";
        public static string Major = "Major";
        public static string Level = "Level";
        public static string Classification = "Classification";
        public static string Full_PartTime = "Full_PartTime";
        public static string EffectiveDate = "EffectiveDate";
        public static string Year = "Year";
        public static string ThesisTitle = "ThesisTitle";
        public static string ThesisStatus = "ThesisStatus";
        public static string LevelGPA = "LevelGPA";
        public static string NumberOfActiveTerms = "NumberOfActiveTerms";
        public static string GraduationTerm = "GraduationTerm";
        public static string CreatedOn = "CreatedOn";
        public static string CreatedBy = "CreatedBy";
        public static string UpdatedOn = "UpdatedOn";
        public static string UpdatedBy = "UpdatedBy";
        public static string Active_flag = "Active_flag";
        public static string Deleted_flag = "Deleted_flag";
        #endregion
    }


    public partial class GraduateStudentController
    {
        #region Fields
        public int GraduateStudentID { get; set; }
        public double? AdvisorID { get; set; }
        public string StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentDepartmentCode { get; set; }
        public string Nationality { get; set; }
        public string Degree { get; set; }
        public string Major { get; set; }
        public string Level { get; set; }
        public string Classification { get; set; }
        public string Full_PartTime { get; set; }
        public DateTime? EffectiveDate { get; set; }
        public int? Year { get; set; }
        public string ThesisTitle { get; set; }
        public string ThesisStatus { get; set; }
        public double? LevelGPA { get; set; }
        public int? NumberOfActiveTerms { get; set; }
        public int? GraduationTerm { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool? Active_flag { get; set; }
        public bool? Deleted_flag { get; set; }
        #endregion

        #region Methods
        #endregion
    }
}
