//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;

    public partial class clsPatent_Issued_Author
    {
        #region Fields
        public static string Patent_Issued_Author_ID = "Patent_Issued_Author_ID";
        public static string Patent_Issued_ID = "Patent_Issued_ID";
        public static string Patent_Number = "Patent_Number";
        public static string KFUPMID = "KFUPMID";
        public static string Remarks = "Remarks";
        public static string CreatedOn = "CreatedOn";
        public static string CreatedBy = "CreatedBy";
        public static string UpdatedOn = "UpdatedOn";
        public static string UpdatedBy = "UpdatedBy";
        public static string Active_flag = "Active_flag";
        public static string Deleted_flag = "Deleted_flag";

        public static string Patent_Issued = "Patent_Issued";
        #endregion
    }


    public partial class Patent_Issued_AuthorController
    {
        #region Fields
        public int Patent_Issued_Author_ID { get; set; }
        public int Patent_Issued_ID { get; set; }
        public string Patent_Number { get; set; }
        public double? KFUPMID { get; set; }
        public string Remarks { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool? Active_flag { get; set; }
        public bool? Deleted_flag { get; set; }

        public virtual Patent_IssuedController Patent_Issued { get; set; }
        #endregion

        #region Methods
        #endregion
    }
}
