//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;

    public partial class Project
    {
        public Nullable<int> Project_ID { get; set; }
        public string Project_Code { get; set; }
        public string Project_Type { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<double> Duration { get; set; }
        public string Extension { get; set; }
        public string Year { get; set; }
        public string Academic_Year { get; set; }
        public Nullable<double> Budget { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> Active_flag { get; set; }
        public Nullable<bool> Deleted_flag { get; set; }

        public virtual Proposal Proposal { get; set; }
    }
}
