//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using App_Code;
    using System;
    using System.Data;
    using System.Data.SqlClient;
    public partial class clsPublication_ISI_Author
    {
        #region Fields
        public static string Publication_ISI_Author_ID = " Publication_ISI_Author_ID ";
        public static string KFUPMID = " KFUPMID ";
        public static string WOS_Number = "WOS_Number";
        public static string Number_Of_Authors = "Number_Of_Authors";
        public static string Authorship_Order = "Authorship_Order";
        public static string Publication_Points = "Publication_Points";
        public static string Project_Code = "Project_Code";
        public static string isCorresponding_Author = "isCorresponding_Author";
        public static string Verified = "Verified=";
        public static string CreatedOn = "CreatedOn";
        public static string CreatedBy = "CreatedBy";
        public static string UpdatedOn = "UpdatedOn";
        public static string UpdatedBy = "UpdatedBy";
        public static string Active_flag = "Active_flag";
        public static string Deleted_flag = "Deleted_flag";
        #endregion
    }

    public partial class Publication_ISI_AuthorController
    {
        #region Fields
        public int Publication_ISI_Author_ID { get; set; }
        public double? KFUPMID { get; set; }
        public string WOS_Number { get; set; }
        public int? Number_Of_Authors { get; set; }
        public double? Authorship_Order { get; set; }
        public double? Publication_Points { get; set; }
        public string Project_Code { get; set; }
        public bool? isCorresponding_Author { get; set; }
        public bool Verified { get; set; }
        public DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool? Active_flag { get; set; }
        public bool? Deleted_flag { get; set; }
        #endregion

        #region Methods
        public static DataTable GetStatsForPublicationPoints()
        {
            string strStoredProcedureName = "sp_rep_GetStatsForPublicationPoints";

            DataTable dt = DbAccess.ExecuteQuery(strStoredProcedureName, CommandType.StoredProcedure);

            return dt;
        }
        public static DataTable GetStatsForPublicationPointsByCollege(string college_code)
        {
            string strStoredProcedureName = "sp_rep_GetStatsForPublicationPointsByCollege";

            SqlParameter param = (new SqlParameter("@college_code", college_code));

            DataTable dt = DbAccess.ExecuteQuery(strStoredProcedureName, CommandType.StoredProcedure, param);

            return dt;
        }
        public static DataTable GetStatsForPublicationPointsByDepartment(string dept_code)
        {
            string strStoredProcedureName = "sp_rep_GetStatsForPublicationPointsByDepartment";

            SqlParameter param = (new SqlParameter("@dept_code", dept_code));

            DataTable dt = DbAccess.ExecuteQuery(strStoredProcedureName, CommandType.StoredProcedure, param);

            return dt;
        }
        public static DataTable GetStatsForPublicationPointsByFaculty(int id)
        {
            string strStoredProcedureName = "sp_rep_GetStatsForPublicationPointsByFaculty";

            SqlParameter param = (new SqlParameter("@id", id));

            DataTable dt = DbAccess.ExecuteQuery(strStoredProcedureName, CommandType.StoredProcedure, param);

            return dt;
        }
        #endregion
    }
}
