//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using App_Code;
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.Data.SqlClient;
    using System.Linq;

    public partial class clsPublication_NonISI
    {
        #region Fields
        public static string Publication_NonISI_ID = "Publication_ISI_Author_ID";
        public static string KFUPMID = "KFUPMID";
        public static string DOI = "WOS_Number";
        public static string Authors = "Number_Of_Authors";
        public static string Paper_Title = "Authorship_Order";
        public static string Source = "Publication_Points";
        public static string Publication_Year = "Project_Code";
        public static string Approved = "isCorresponding_Author";
        public static string isCorresponding_Author = "Verified=";
        public static string CreatedOn = "CreatedOn";
        public static string CreatedBy = "CreatedBy";
        public static string UpdatedOn = "UpdatedOn";
        public static string UpdatedBy = "UpdatedBy";
        public static string Active_flag = "Active_flag";
        public static string Deleted_flag = "Deleted_flag";
        #endregion
    }

    public partial class Publication_NonISIController
    {
        #region Fields
        public int Publication_NonISI_ID { get; set; }
        public double KFUPMID { get; set; }
        public string DOI { get; set; }
        public string Authors { get; set; }
        public string Paper_Title { get; set; }
        public string Source { get; set; }
        public int? Publication_Year { get; set; }
        public bool? Approved { get; set; }
        public bool? isCorrespondingAuthor { get; set; }
        public DateTime? CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public bool? Active_flag { get; set; }
        public bool? Deleted_flag { get; set; }
        #endregion

        #region Methods
        public static List<Publication_NonISIController> getNonISIPublicationsAll()
        {
            string strStoredProcedureName = "sp_rep_getNonISIPublicationsAll";                       

            DataTable dt = DbAccess.ExecuteQuery(strStoredProcedureName, CommandType.StoredProcedure);

            return helper(dt);
        }
        public static List<Publication_NonISIController> getNonISIPublicationsByFaculty(int id)
        {
            string strStoredProcedureName = "sp_rep_getNonISIPublicationsByFaculty";

            SqlParameter param = new SqlParameter();
            param.ParameterName = "@id";
            param.SqlDbType = SqlDbType.Int;
            param.Value = id;

            DataTable dt = DbAccess.ExecuteQuery(strStoredProcedureName, CommandType.StoredProcedure, param);

            return helper(dt);
            
        }
        public static List<Publication_NonISIController> getNonISIPublicationsByCollege(string college_code)
        {
            string strStoredProcedureName = "sp_rep_getNonISIPublicationsByCollege";

            SqlParameter param = new SqlParameter();
            param.ParameterName = "@college_code";
            param.SqlDbType = SqlDbType.Char;
            param.Value = college_code;

            DataTable dt = DbAccess.ExecuteQuery(strStoredProcedureName, CommandType.StoredProcedure, param);

            return helper(dt);
        }
        public static List<Publication_NonISIController> getNonISIPublicationsByDepartment(string dept_code)
        {
            string strStoredProcedureName = "sp_rep_getNonISIPublicationsByDepartment";

            SqlParameter param = new SqlParameter();
            param.ParameterName = "@dept_code";
            param.SqlDbType = SqlDbType.Char;
            param.Value = dept_code;

            DataTable dt = DbAccess.ExecuteQuery(strStoredProcedureName, CommandType.StoredProcedure, param);

            return helper(dt);
        }

        private static List<Publication_NonISIController> helper(DataTable dt)
        {
            var list = dt.AsEnumerable()
                .Select(dr =>
                new Publication_NonISIController
                {
                    Publication_NonISI_ID = dr.Field<int>("Publication_NonISI_ID"),
                    DOI = dr.Field<string>("DOI"),
                    KFUPMID = dr.Field<double>("KFUPMID"),
                    Authors = dr.Field<string>("Authors"),
                    Paper_Title = dr.Field<string>("Paper_Title"),
                    Source = dr.Field<string>("Source"),
                    Publication_Year = dr.Field<int?>("Publication_Year"),
                    Approved = dr.Field<bool?>("Approved"),
                    isCorrespondingAuthor = dr.Field<bool?>("isCorrespondingAuthor"),
                    //Deleted_flag = dr.Field<bool?>("Deleted_flag"),
                    //Active_flag = dr.Field<bool?>("Active_flag"),
                    //CreatedBy = dr.Field<string>("CreatedBy"),
                    //CreatedOn = dr.Field<System.DateTime>("CreatedOn")
                }
                ).ToList();

            return list;
        }
        #endregion

    }
}
